---
# This Playbook would deploy the whole mongodb cluster with replication and sharding.

- name: common
  hosts: all
  roles:
  - role: common

- name: mongod
  hosts: mongo_servers
  roles:
  - role: mongod
