---
# This Playbook would deploy the whole mongodb cluster with replication and sharding.

- name: common
  hosts: all
  roles:
  - role: common

- name: mongod
  hosts: mongo_servers
  roles:
  - role: mongod

#- hosts: mongoc_servers
#  roles:
#  - role: mongoc

- name: mongos
  hosts: mongos_servers
  roles:
  - role: mongos

- name: shards
  hosts: mongo_servers
  tasks:
  - include: roles/mongod/tasks/shards.yml
